### ISSUE TITLE
ceph_client role should configure libvirt secret so nova works

### ISSUE THREAD

**Issue by fultonj** [fmount/tripleo-ceph#16]
/var/log/containers/nova/nova-api.log:2020-06-02 11:46:04.932 23 INFO nova.api.openstack.compute.server_external_events [req-d4549eec-6f15-4433-ab52-65cc356e5c41 59da4ca368aa468588b6aed95d7853f3 3db198b72fb441c49d950ea49bb9abba - default default] Creating event network-changed:1e8b9745-5cc5-472d-a3b8-7cd5240b7d67 for instance ecd97bd0-f2ef-422c-b347-ccd2b1033433 on oc0-compute-1.localdomain
/var/log/containers/nova/nova-conductor.log:2020-06-02 11:46:10.911 6 ERROR nova.scheduler.utils [req-f2e1da32-4bab-4673-879b-45a82d0ba3f7 555ce74bd67c4c18be2515b512220050 1d037149fefb48d982b1f82d3420d8de - default default] [instance: ecd97bd0-f2ef-422c-b347-ccd2b1033433] Error from last host: oc0-compute-1.localdomain (node oc0-compute-1.localdomain): ['Traceback (most recent call last):\n', '  File "/usr/lib/python3.6/site-packages/nova/compute/manager.py", line 2378, in _build_and_run_instance\n    accel_info=accel_info)\n', '  File "/usr/lib/python3.6/site-packages/nova/virt/libvirt/driver.py", line 3625, in spawn\n    cleanup_instance_disks=created_disks)\n', '  File "/usr/lib/python3.6/site-packages/nova/virt/libvirt/driver.py", line 6524, in _create_domain_and_network\n    cleanup_instance_disks=cleanup_instance_disks)\n', '  File "/usr/lib/python3.6/site-packages/oslo_utils/excutils.py", line 220, in __exit__\n    self.force_reraise()\n', '  File "/usr/lib/python3.6/site-packages/oslo_utils/excutils.py", line 196, in force_reraise\n    six.reraise(self.type_, self.value, self.tb)\n', '  File "/usr/lib/python3.6/site-packages/six.py", line 703, in reraise\n    raise value\n', '  File "/usr/lib/python3.6/site-packages/nova/virt/libvirt/driver.py", line 6493, in _create_domain_and_network\n    post_xml_callback=post_xml_callback)\n', '  File "/usr/lib/python3.6/site-packages/nova/virt/libvirt/driver.py", line 6429, in _create_domain\n    guest.launch(pause=pause)\n', '  File "/usr/lib/python3.6/site-packages/nova/virt/libvirt/guest.py", line 142, in launch\n    self._encoded_xml, errors=\'ignore\')\n', '  File "/usr/lib/python3.6/site-packages/oslo_utils/excutils.py", line 220, in __exit__\n    self.force_reraise()\n', '  File "/usr/lib/python3.6/site-packages/oslo_utils/excutils.py", line 196, in force_reraise\n    six.reraise(self.type_, self.value, self.tb)\n', '  File "/usr/lib/python3.6/site-packages/six.py", line 703, in reraise\n    raise value\n', '  File "/usr/lib/python3.6/site-packages/nova/virt/libvirt/guest.py", line 137, in launch\n    return self._domain.createWithFlags(flags)\n', '  File "/usr/lib/python3.6/site-packages/eventlet/tpool.py", line 190, in doit\n    result = proxy_call(self._autowrap, f, *args, **kwargs)\n', '  File "/usr/lib/python3.6/site-packages/eventlet/tpool.py", line 148, in proxy_call\n    rv = execute(f, *args, **kwargs)\n', '  File "/usr/lib/python3.6/site-packages/eventlet/tpool.py", line 129, in execute\n    six.reraise(c, e, tb)\n', '  File "/usr/lib/python3.6/site-packages/six.py", line 703, in reraise\n    raise value\n', '  File "/usr/lib/python3.6/site-packages/eventlet/tpool.py", line 83, in tworker\n    rv = meth(*args, **kwargs)\n', '  File "/usr/lib64/python3.6/site-packages/libvirt.py", line 1166, in createWithFlags\n    if ret == -1: raise libvirtError (\'virDomainCreateWithFlags() failed\', dom=self)\n', 'libvirt.libvirtError: internal error: qemu unexpectedly closed the monitor: 2020-06-02T11:46:07.177308Z qemu-kvm: -drive file=rbd:vms/ecd97bd0-f2ef-422c-b347-ccd2b1033433_disk:id=openstack:auth_supported=cephx\\;none:mon_host=172.16.11.56\\:6789\\;172.16.11.126\\:6789\\;172.16.11.80\\:6789\\;172.16.11.127\\:6789\\;172.16.11.123\\:6789,file.password-secret=virtio-disk0-secret0,format=raw,if=none,id=drive-virtio-disk0,cache=writeback,discard=unmap: error connecting: Permission denied\n', '\nDuring handling of the above exception, another exception occurred:\n\n', 'Traceback (most recent call last):\n', '  File "/usr/lib/python3.6/site-packages/nova/compute/manager.py", line 2200, in _do_build_and_run_instance\n    filter_properties, request_spec, accel_uuids)\n', '  File "/usr/lib/python3.6/site-packages/nova/compute/manager.py", line 2478, in _build_and_run_instance\n    instance_uuid=instance.uuid, reason=six.text_type(e))\n', 'nova.exception.RescheduledException: Build of instance ecd97bd0-f2ef-422c-b347-ccd2b1033433 was re-scheduled: internal error: qemu unexpectedly closed the monitor: 2020-06-02T11:46:07.177308Z qemu-kvm: -drive file=rbd:vms/ecd97bd0-f2ef-422c-b347-ccd2b1033433_disk:id=openstack:auth_supported=cephx\\;none:mon_host=172.16.11.56\\:6789\\;172.16.11.126\\:6789\\;172.16.11.80\\:6789\\;172.16.11.127\\:6789\\;172.16.11.123\\:6789,file.password-secret=virtio-disk0-secret0,format=raw,if=none,id=drive-virtio-disk0,cache=writeback,discard=unmap: error connecting: Permission denied\n']

**Comment by fultonj** [comment]
It seems a secret was configured by TripleO on the Nova side:
```
[root@oc0-compute-2 ~]# podman exec -ti nova_libvirt grep -v \# /etc/nova/nova.conf | grep rbd
images_type=rbd
images_rbd_pool=vms
images_rbd_ceph_conf=/etc/ceph/ceph.conf
rbd_user=openstack
rbd_secret_uuid=67b299c8-cfbb-4bcd-b99c-80aec1847213
[root@oc0-compute-2 ~]# 
```
I can see the same secret UUID here:
```
[root@oc0-compute-0 libvirt]# podman exec -ti nova_libvirt virsh secret-list
 UUID                                   Usage
----------------------------------------------------------------------
 67b299c8-cfbb-4bcd-b99c-80aec1847213   ceph client.openstack secret

[root@oc0-compute-0 libvirt]# 

[root@oc0-compute-0 libvirt]# cat /var/lib/config-data/nova_libvirt/etc/nova/secret.xml
<secret ephemeral='no' private='no'>
  <usage type='ceph'>
    <name>client.openstack secret</name>
  </usage>
  <uuid>67b299c8-cfbb-4bcd-b99c-80aec1847213</uuid>
</secret>
[root@oc0-compute-0 libvirt]# 
```
In /var/log/containers/libvirt/libvirtd.log.1 I see the following error:
```
[root@oc0-compute-0 libvirt]# cat libvirtd.log.1 
2020-06-01 21:08:12.822+0000: 32201: info : libvirt version: 5.6.0, package: 10.el8 (CBS <cbs@centos.org>, 2020-02-27-01:09:46, )
2020-06-01 21:08:12.822+0000: 32201: info : hostname: oc0-compute-0
2020-06-01 21:08:12.822+0000: 32201: error : qemuMonitorIORead:604 : Unable to read from monitor: Connection reset by peer
2020-06-01 21:08:12.823+0000: 32201: error : qemuProcessReportLogError:2098 : internal error: qemu unexpectedly closed the monitor: 2020-06-01T21:08:12.500334Z qemu-kvm: -drive file=rbd:vms/10202edd-418d-49dc-8fd5-11bbac00ac75_disk:id=openstack:auth_supported=cephx\;none:mon_host=172.16.11.56\:6789\;172.16.11.126\:6789\;172.16.11.80\:6789\;172.16.11.127\:6789\;172.16.11.123\:6789,file.password-secret=virtio-disk0-secret0,format=raw,if=none,id=drive-virtio-disk0,cache=writeback,discard=unmap: error connecting: Permission denied
2020-06-01 21:47:38.427+0000: 49719: info : libvirt version: 5.6.0, package: 10.el8 (CBS <cbs@centos.org>, 2020-02-27-01:09:46, )
2020-06-01 21:47:38.427+0000: 49719: info : hostname: oc0-compute-0
2020-06-01 21:47:38.427+0000: 49719: error : virNetSocketReadWire:1851 : End of file while reading data: Input/output error
[root@oc0-compute-0 libvirt]# 
```

**Comment by fultonj** [comment]
Within the libvirt container it has no problem using the same key to read/write/delete from vms pool:
```
podman exec nova_libvirt rbd --conf /etc/ceph/ceph.conf --keyring /etc/ceph/ceph.client.openstack.keyring --id openstack ls vms
```
The error from libvirtd was this if we break it up a little:
```
[root@oc0-compute-0 libvirt]# 

qemu-kvm: -drive 

file=rbd:vms/ce7e87fb-f2b1-4e6c-bc61-647819bdc633_disk:id=openstack:auth_supported=cephx\;none:mon_host=172.16.11.56\:6789\;172.16.11.126\:6789\;172.16.11.80\:6789\;172.16.11.127\:6789\;172.16.11.123\:6789,file.password-secret=virtio-disk0-secret0,format=raw,if=none,id=drive-virtio-disk0,cache=writeback,discard=unmap: 

error connecting: Permission denied
```
Note that it knew of all 5 mons even though the ceph.conf only has one listed from the first mon. I assume it must have started the conversation with ceph to be told of the others. 
```
172.16.11.56\:6789\;
172.16.11.126\:6789\;
172.16.11.80\:6789\;
172.16.11.127\:6789\;
172.16.11.123\:6789,
```
Let's get the libvirt logs in debug mode:
```
ssh compute-0
cd /var/lib/config-data/puppet-generated/nova_libvirt/etc/libvirt/
grep -n log_outputs virtlogd.conf  libvirtd.conf 
```
set them both to 1 for debug
```
 systemctl restart tripleo_nova_libvirt.service
```
Here's a message from libvirt when it fails:

 http://paste.openstack.org/show/794390/

**Comment by fultonj** [comment]
Unfortunately I need to rebuild the environment where I've reproduced this in order to fix higher priority bugs. Thus, if I'm unable to reproduce this later I might close it. It might be simpler to just use ceph-ansible's key module to set up the clients anyway.
